= Git Commit Message
:author: hituzi no sippo
:email: dev@hituzi-no-sippo.me
:revnumber: v0.5.0
:revdate: 2022-07-11T20:58:35+09:00
:revremark: Add GitHub Actions
:description: Git commit message tools
:copyright: Copyright (C) 2022 {author}
// Custom Attributes
:creation_date: 2022-07-11T15:36:50+09:00
:project_root_directory_path: ../../..

Git commit messages conform to link:https://www.conventionalcommits.org[
Conventional Commits^].

== Linter

:cocogitto_url: https://docs.cocogitto.io
Using link:{cocogitto_url}[Cocogitto^].

:cocogitto_documentation_url: https://docs.cocogitto.io/guide
=== Configuration

link:{project_root_directory_path}/cog.toml[Configuration File^]

.Ignore Merge Commit
Cocogitto ignores merge commit
(e.g. `Merge branch 'main' ...`, `Merge pull request ...`).
link:{cocogitto_documentation_url}#deal-with-merge-commits[
This is because `ignore_merge_commits = true` is set the configuration file^].

=== Git Hooks

.`commit-msg` hook
Lint commit message (i.e. `cog verify "$MESSAGE"`) on git `commit-msg` hook.
link:{cocogitto_documentation_url}#built-in-git-hooks[
This is because setup `<PROJECT_ROOT>/.git/hooks/commit-msg` with
`cog install-hook commit-msg`^] on link:{project_root_directory_path}/scripts/setup.sh#:~:text=cog%20install%2Dhook%20commit%2Dmsg[
setup shell].

=== GitHub Actions

:filename: lint-git-commit-message.yml
link:{project_root_directory_path}/.github/workflows/{filename}[{filename}^]

Lint commit message (i.e. `cog check --from-latest-tag`) with link:https://github.com/marketplace/actions/conventional-commit-cocogitto-action[
cocogitto-action^].


'''

:author_link: link:https://github.com/hituzi-no-sippo[{author}^]
Copyright (C) 2022 {author_link}
