---
name: Lint Shell on Pull Request

on:
  pull_request:
    paths:
      - "**.sh"

jobs:
  format:
    name: Format
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run shfmt with reviewdog
        uses: reviewdog/action-shfmt@v1
        with:
          # default is '-i 2 -ci'
          shfmt_flags: ""
