---
name: Lint YAML

on:
  push:
    paths:
      - "**.ya?ml"
      - ".dprint.json"
      - ".yamllint.yml"
  pull_request:
    paths:
      - "**.ya?ml"
      - ".dprint.json"
      - ".yamllint.yml"

jobs:
  format:
    name: Format
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Format Check with dprint
        uses: hituzi-no-sippo/check@21681de30f5916de2235da7f22bf7462bb7004cb
        with:
          file-patterns: '"**/*.{yml,yaml}"'

  lint:
    name: Lint
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run yamllint with reviewdog
        uses: reviewdog/action-yamllint@v1
        with:
          reporter: github-pr-review

      # https://yamllint.readthedocs.io/en/stable/integration.html#integration-with-github-actions
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML files with yamllint
        run: yamllint --strict --format=github .
