---
name: Lint Markdown

on:
  push:
    paths:
      - "**.md"
      - ".dprint.json"
  pull_request:
    paths:
      - "**.md"
      - ".dprint.json"

jobs:
  format:
    name: Format
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check format with dprint
        uses: hituzi-no-sippo/check@21681de30f5916de2235da7f22bf7462bb7004cb
        with:
          file-patterns: '"**/*.md"'

  lint:
    name: Lint
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: xt0rted/markdownlint-problem-matcher@v1

      - name: Lint Markdown files
        uses: docker://davidanson/markdownlint-cli2:v0.5.0
