---
name: Lint CHANGELOG.md

on:
  push:
    paths:
      - .git-cliff/release-note.toml
  pull_request:
    paths:
      - .git-cliff/release-note.toml

jobs:
  lint:
    name: Lint CHANGELOG.md
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Get the full git history to generate Release Note with git-cliff.
          fetch-depth: 0

      - name: Set up git-cliff
        uses: kenji-miyake/setup-git-cliff@v1
      - name: Generate release note with git-cliff
        run: |
          git-cliff --latest \
            --config .git-cliff/release-note.toml \
            --output release-note.md

      # avtodev/markdown-lint:v1 haven't disable rule option
      - name: Disable markdownlint MD024
        run: "echo 'MD024: false' > .markdownlint.yaml"

      - name: Lint CHANGELOG.md
        uses: docker://avtodev/markdown-lint:v1
        with:
          args: release-note.md
