---
name: Lint YAML

on: [push, pull_request]

jobs:
  format:
    name: Format
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Prettier with reviewdog
        uses: EPMatt/reviewdog-action-prettier@v1
        with:
          level: warning
          reporter: github-pr-review
          prettier_flags: "**/*.(yml|yaml)"
      - name: Format Check with Prettier
        uses: creyD/prettier_action@v4.2
        with:
          dry: true
          prettier_options: --check **/*.(yml|yaml)
  lint:
    name: Lint
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # https://yamllint.readthedocs.io/en/stable/integration.html#integration-with-github-actions
      - name: Setup Python
        uses: actions/setup-python@v3
      - name: Install yamllint
        run: pip install yamllint
      - name: Lint YAML Files with yamllint
        run: yamllint --strict --format=github .
