---
name: Lint JSON

on:
  push:
    paths:
      - "**.json"
      - ".dprint.json"
  pull_request:
    paths:
      - "**.json"
      - ".dprint.json"

jobs:
  format:
    name: Format
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Format Check with dprint
        uses: hituzi-no-sippo/check@21681de30f5916de2235da7f22bf7462bb7004cb
        with:
          file-patterns: '"**/*.json"'
